FROM python:3.9-slim

WORKDIR /app

# Copy requirements
# COPY requirements.txt .

# Install Python dependencies
# RUN pip install --no-cache-dir -r requirements.txt

# Install additional packages for Stream Redirect Server
RUN pip install flask flask-cors requests gunicorn eventlet

# Copy source code
COPY multi_server_gateway/stream_redirect_server.py /app/
COPY multi_server_gateway/stream_redirect_config.json /app/

COPY logging_config.py /app/

# Create logs directory
RUN mkdir -p logs

# Expose port
EXPOSE 4001

# Set environment variables     
ENV PYTHONPATH=/app

# Run the Stream Redirect Server
CMD ["gunicorn", "--worker-class", "eventlet", "-w", "5", "--bind", "0.0.0.0:4001", "stream_redirect_server:app"]

# docker build -f Dockerfile.multi_stream_redirect -t pcs_ww_multi_stream_redirect .
# docker run  -d -p 4001:4001 --name pcs_ww_multi_stream_redirect pcs_ww_multi_stream_redirect:latest